import type { BlockNode, BlockProgram, Condition, NanoProject } from '../../types/nano'
import { getComponentDef } from '../../data/components'
import { resolvePinMap } from '../circuit/topology'

/**
 * Block → C/C++ generation.
 * Deterministic and readable — students are meant to read this code
 * side-by-side with their blocks.
 */

const DEFAULT_LED_PIN = 13
const DEFAULT_BUZZER_PIN = 8

function conditionToCpp(condition: Condition): string {
  const right =
    typeof condition.right === 'number'
      ? String(condition.right)
      : condition.right.replace(/^var:/, '')
  return `${condition.leftVariable} ${condition.op} ${right}`
}

/** All set-output targets in program order (deduplicated). */
function collectOutputTargets(nodes: BlockNode[], into: string[]): void {
  for (const node of nodes) {
    if (node.type === 'if-else') {
      collectOutputTargets(node.then, into)
      collectOutputTargets(node.else, into)
    } else if (node.type === 'set-output' && !into.includes(node.targetId)) {
      into.push(node.targetId)
    }
  }
}

export interface CodegenResult {
  code: string
  /** Placed-component ids the generated program drives. */
  outputs: string[]
}

export function generateCode(project: NanoProject): CodegenResult {
  const pinMap = resolvePinMap(project.circuit)
  const program: BlockProgram = project.blocks

  // 1) Resolve every driven component to a C constant + concrete pin.
  const targets: string[] = []
  collectOutputTargets(program.loop, targets)

  const constLines: string[] = []
  const targetInfo = new Map<string, { constName: string; label: string }>()

  let ledIndex = 0
  let buzzerAssigned = false
  for (const targetId of targets) {
    const placed = project.circuit.components.find((c) => c.id === targetId)
    const def = placed ? getComponentDef(placed.defId) : undefined
    if (!placed || !def) continue

    if (def.simulationType === 'led') {
      ledIndex += 1
      const constName = ledIndex === 1 ? 'LED_PIN' : `LED_PIN_${ledIndex}`
      const traced = pinMap.ledPins[targetId]
      const concrete = traced && /^D\d+$/.test(traced) ? Number(traced.slice(1)) : DEFAULT_LED_PIN
      constLines.push(`const int ${constName} = ${concrete};  // ${placed.label}`)
      targetInfo.set(targetId, { constName, label: placed.label })
    } else if (def.simulationType === 'buzzer') {
      const constName = 'BUZZER_PIN'
      if (!buzzerAssigned) {
        constLines.push(`const int ${constName} = ${DEFAULT_BUZZER_PIN};  // ${placed.label}`)
        buzzerAssigned = true
      }
      targetInfo.set(targetId, { constName, label: placed.label })
    }
  }

  if (program.loop.some((n) => n.type === 'read-sensor' && n.sensor === 'light') && pinMap.ldrPin) {
    constLines.unshift(`const int LDR_PIN = ${pinMap.ldrPin};`)
  }
  if (program.loop.some((n) => n.type === 'read-sensor' && n.sensor === 'knob') && pinMap.knobPin) {
    constLines.unshift(`const int KNOB_PIN = ${pinMap.knobPin};`)
  }

  // 2) Emit statements.
  const body = emitNodes(program.loop, targetInfo, 0)

  const setupLines = ['  Serial.begin(9600);']
  for (const [, info] of targetInfo) {
    setupLines.push(`  pinMode(${info.constName}, OUTPUT);`)
  }

  const loopBody = body.length > 0 ? body : ['  // Add blocks in the Blocks tab']

  const code = [
    '// Generated by Nano Spark IDE',
    '// Board: Arduino UNO',
    '',
    ...(constLines.length ? [...constLines, ''] : []),
    'void setup() {',
    ...setupLines,
    '}',
    '',
    'void loop() {',
    ...loopBody,
    '}',
    '',
  ].join('\n')

  return { code, outputs: [...targetInfo.keys()] }
}

function indent(depth: number): string {
  return '  '.repeat(depth + 1)
}

function emitNodes(
  nodes: BlockNode[],
  targetInfo: Map<string, { constName: string; label: string }>,
  depth: number,
): string[] {
  const lines: string[] = []
  const pad = indent(depth)

  for (const node of nodes) {
    switch (node.type) {
      case 'read-sensor': {
        lines.push(`${pad}int ${node.variable} = analogRead(${node.sensor === 'light' ? 'LDR_PIN' : 'KNOB_PIN'});`)
        break
      }
      case 'set-output': {
        const info = targetInfo.get(node.targetId)
        if (!info) break
        const value = node.state === 'on' ? 'HIGH' : 'LOW'
        lines.push(`${pad}digitalWrite(${info.constName}, ${value});  // ${info.label}`)
        break
      }
      case 'delay':
        lines.push(`${pad}delay(${node.ms});`)
        break
      case 'if-else': {
        lines.push(`${pad}if (${conditionToCpp(node.condition)}) {`)
        const thenLines = emitNodes(node.then, targetInfo, depth + 1)
        if (thenLines.length > 0) lines.push(...thenLines)
        else lines.push(`${indent(depth + 1)}// then…`)
        lines.push(`${pad}}`)
        if (node.else.length > 0) {
          lines.push(`${pad}else {`)
          lines.push(...emitNodes(node.else, targetInfo, depth + 1))
          lines.push(`${pad}}`)
        }
        break
      }
    }
  }
  return lines
}
